import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const twenTigthCentury = localFont({
  src: [
    {
      path: "../app/fonts/TwentiethCenturyforKenmoreN.ttf",
      weight: "normal",
      style: "normal",
    },
    {
      path: "../app/fonts/TwentiethCenturyforKenmoreNBold.ttf",
      weight: "bold",
      style: "normal",
    },
  ],
  variable: "--font-twentieth-century",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${twenTigthCentury.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

// ${geistSans.variable} ${geistMono.variable}
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
